version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: group_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: XFbhjuL2?
      MYSQL_DATABASE: clinic_db
      MYSQL_USER: groupuser
      MYSQL_PASSWORD: grouppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: groupuser
      DB_PASSWORD: grouppass
      DB_NAME: clinic_db

volumes:
  db_data: